### PR TITLE
Implemented a protocol for reading data from the switch.

### PR DESCRIPTION
**Pull request by peci1**
The commands for reading have PHY=102.
With REG=1, it reads values via MDIO. PHY and REG to read are set in the 2 data bytes.
With REG=2, it reads from EEPROM. The index to read is the first byte of data.
With REG=3, it reads from Commands_Total (RAM). The index to read is the first byte of data.
Returned is first the success byte, and then 4 bytes in the same format as commands [PHY, REG, DataByteHigh, DataByteLow].

Command with PHY=103 returns the success byte and then one byte with firmware revision number.

Command with PHY=104 returns the success byte and then 's' denoting this is a SwitchBlox.

This PR depends on #12 and #13.

### CODE REVIEW

**Comment by peci1** [comment]
Experimental client library support in `readback` branch of https://github.com/peci1/botblox-manager-software/tree/readback .

**Comment by peci1** [comment]
Read an MII register of the IP175G:

```
$ python3.8 -m botblox_config -D /dev/ttyUSB0 read_switch 23 1
DEBUG:root:Data to be sent (excl. "stop" command): 
DEBUG:root:------------------------------------------
DEBUG:root:[[102, 1, 23, 1]]
DEBUG:root:------------------------------------------
INFO:root:Success reading configuration from switch
INFO:root:Successful configuration
DEBUG:root:Data returned (without success flag): 
DEBUG:root:------------------------------------------
DEBUG:root:[23, 1, 220, 0]
DEBUG:root:------------------------------------------
INFO:root:Data read from switch is [23, 1, 220, 0]
```

**Comment by peci1** [comment]
Dump whole EEPROM:

```
$ for i in `seq 0 19`; do python3.8 -m botblox_config -D /dev/ttyUSB0 read_config $i 2>/dev/null; done
[23, 0, 0, 0]
[23, 1, 220, 0]
[23, 2, 255, 4]
[23, 7, 131, 0]
[23, 8, 131, 0]
[23, 9, 1, 0]
[23, 11, 131, 0]
[23, 12, 131, 0]
[23, 13, 16, 0]
[23, 14, 204, 0]
[24, 0, 1, 0]
[24, 1, 131, 0]
[24, 17, 220, 255]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
```

**Comment by AaronElijah** [comment]
I really, really like what you've done here @peci1! It's simple and very close to what we discussed a while ago about adding read operations. I'm going to merge this. Thank you!

**Pull request merged**
